# Generated by Django 2.1.4 on 2019-01-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kick', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kickstarter',
            old_name='backer_count',
            new_name='backers_count',
        ),
    ]
